### ISSUE TITLE
Meta-Issue for improvements to `@compact`

### ISSUE THREAD

**Issue by avik-pal** [LuxDL/Lux.jl#606]
- [x] #588 for specifying constants directly
- [x] Special syntax for providing functions that are evaluated in `initialparameters` (maybe `@initfn` annotation)
- [x] Allow multiple `@return` using `@goto`
- [ ] **(Very Speculative)** Rewrite Lux Layers with `@compact` for readability. (This is going to be very breaking for how parameters and states are arranged currently)
  - To clarify confusion, the container layers in Lux are **NOT GOING ANYWHERE**; the change, if ever done, will be an internal implementation detail, mostly invisible to the end user.
- [x] ~https://github.com/LuxDL/Lux.jl/issues/692~
