### ISSUE TITLE
Roadmap to v1

### ISSUE THREAD

**Issue by avik-pal** [LuxDL/Lux.jl#735]
## Features

- [x] Move Training utilities out of Experimental. One major recent push has been to clean up the training and ensure it is used everywhere in tutorials. It is about time to guarantee semvar for it.
- [x] ~Preliminary XLA support. Please have a look at LuxDL/Lux.jl#733 for a detailed discussion~
- [x] DispatchDoctor LuxDL/Lux.jl#683. Adding this directly to LuxCore. While not strictly breaking, I want to move this to 0.6. Fixed in https://github.com/LuxDL/Lux.jl/pull/798
- [x] Automatic Eltype warning using preferences. See LuxDL/Lux.jl#727 

## Minor TODOs

- [x] Reexport NNlib from Lux
- [x] ~Remove `xlogy` and `xlogx` in favor of https://github.com/JuliaStats/LogExpFunctions.jl~ See #796 unsafe for GPU broadcasting

## Deprecations

- [x] Flattening of Chains LuxDL/Lux.jl#682 
- [x] Remove unnecessary overloads of `Base.keys`
- [x] Deprecate the TrainState construction using `rng`
- [x] Older versions of preferences (mostly done in LuxDL/Lux.jl#727)
- [x] `cpu`/`gpu`
- [x] `disable_stacktrace_truncation!`
- [x] Experimental symbols present outside Experimental
- [x] Strings in DebugLayer/layer_map
- [x] `Experimental.@compact` and `Experimental.StatefulLuxLayer`
- [x] Not specifying `true/false` in StatefulLuxLayer.

## Underlying packages that need to be updated to 1.0

- [x] LuxCore -- the naming changes is probably too disruptive without any major benefit. We will only do the following 2 name changes: https://github.com/LuxDL/LuxCore.jl/pull/43
  - [x] `AbstractLuxLayer`
  - [x] `AbstractLuxContainerLayer`
- [x] `LuxDeviceUtils` --> `MLDataDevices`
  - [x] Change naming of the package once registered
  - [x] Renaming https://github.com/LuxDL/LuxDeviceUtils.jl/pull/52 
  - [x] Remove Deprecations https://github.com/LuxDL/LuxDeviceUtils.jl/pull/53
- [x] WeightInitializers
  - [x] https://github.com/LuxDL/WeightInitializers.jl/issues/11
- [x] LuxLib
  - [x] Remove reexport of NNlib
  - [x] Remove Deprecations https://github.com/LuxDL/LuxLib.jl/pull/82
- [x] Refactor of LuxTestUtils

## Documentation Updates

- [x] Add a migration guide to 1.0
- [x] Update wording on interface specs. Make it sound mandatory.
- [x] Update WeightInitializers.jl documentation to highlight what RNGs are supported

**Comment by avik-pal** [comment]
Another consideration is whether we should do a 0.6 release or move directly to a 1.0 release. 

I have read posts in the wild complaining about the rapid release, which led to the *.*.57 patches, which might give a (false) notion that we were fixing bugs, but most of them were features :sweat:

**Comment by avik-pal** [comment]
### General Status Updates:

- Boltz documentation has been separated out to allow for easier update
- LuxCore is ready for an update
  - if I don't hear back on anything, I will move ahead with this
- LuxLib is mostly ready
  - let's land the layernorm default change first
- dropping XLA support as milestone since that is non-breaking
